### ISSUE TITLE
Look into GreenKeeper

### ISSUE THREAD

**Issue by domfarolino** [RevolutionUC/revolutionuc-emails#1]
@noahbass 

You mind if I configured GreenKeeper on this repository? https://greenkeeper.io for more information but it is an integration bot that updates dependencies on your project, runs your tests, and if your tests pass with the updated deps it makes a PR for you to approve with package.json updates. Keeps everything up to date so long as your tests pass. I'm using it for what the RevUC website is based off of and think it might be helpful for us since we have tests.

**Comment by noahbass** [comment]
I've seen this in a few open source projects on GH. LGTM⚡️. Add it🎄
