### ISSUE TITLE
Email Verification Template

### ISSUE THREAD

**Issue by domfarolino** [RevolutionUC/revolutionuc-emails#14]
Could you make a template (or just modify the welcome one since we won't need it without email verification). We need it to:

 - Say that we need them to verify their email with us before anything
 - Display a button saying `Verify Email` (or something) that when clicked, redirects the user to a URL that the web backend passes in as template data

**Comment by noahbass** [comment]
Closed via 6cf3293923685ee6c8208eaf9aa4b42e95a72f24
