### ISSUE TITLE
Responsive emails

### ISSUE THREAD

**Issue by noahbass** [RevolutionUC/revolutionuc-emails#3]
At the moment, the email content is tough to read on mobile email clients and some components are out of place (e.g. the logo is left-aligned instead of center-aligned) - see screenshot. Find a way to add better responsive email design and ux for mobile users.

![img_0386](https://cloud.githubusercontent.com/assets/3453188/21582963/14fa243a-d039-11e6-88dd-cd40b7428312.PNG)

**Comment by domfarolino** [comment]
status

**Comment by noahbass** [comment]
Closing as of fixes in [v2.0.0](https://github.com/RevolutionUC/revolutionuc-emails/commit/dae2aa0e8c6edea835724b458d1b7a96058a92da).
